CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8mb4 ;
USE `todo` ;

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `todos` (
  `id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4
COMMENT = '';

SET FOREIGN_KEY_CHECKS=1;
